### ISSUE TITLE
extending a pool that contains a deleted node id

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/tfexplorer#164]
I tried to extend my pool (https://explorer.testnet.grid.tf/api/v1/reservations/pools/1)
but it failed that a node (3BwDVNRigau8Zk6BQkJt5PLxrHQnJ5NTfNvAtuubC1eS) doesn't exist.

excluding the node also failed with error "nodes can't be removed from pool"

![image](https://user-images.githubusercontent.com/32568986/92758963-8aa28100-f38f-11ea-9047-4b171177f8f9.png)
![image](https://user-images.githubusercontent.com/32568986/92758982-8f673500-f38f-11ea-8979-03e4212bf90b.png)

**Comment by zaibon** [comment]
Lee Smet, [10.09.20 17:42]
I thought nodes could not be deleted on the explorer?

Zaibon, [10.09.20 17:44]
?

Zaibon, [10.09.20 17:44]
Yes they can

Zaibon, [10.09.20 17:45]
But maybe that's the issue. And node should just be tombestoned

Lee Smet, [10.09.20 17:52]
The current implementation indeed assumes that dead nodes are still available in the explorer. We can work around this, but then we first need to do some thinking regarding the security considerations imo. The current code flow relies on this behavior to prevent exploits

Zaibon, [10.09.20 17:55]
I think it's indeed better to keep them and just mark them dead

**Comment by zaibon** [comment]
What I propose:
- [ ] change the [deleteNodeFromFarm](https://github.com/threefoldtech/tfexplorer/blob/4b54d255ce80f8f016a1b55cc5e5b56ab23d1506/pkg/directory/farms_handlers.go#L149) method to mark the node as deleted instead of actually delete it from the db
- [ ] adapt all the method listing node to not return the node marked as deleted
  - [ ] add an extra query argument to include the deleted nodes (do we want this ?)
- [ ] review pool code path to make sure we properly support deleted nodes
