### ISSUE TITLE
Only delete workloads that are actually out of resource instead of automatically deleting all workload from a pool when one of the resource is exhausted

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#171]
Right now, We make use of empty pools for gateways, networks, .. etc, we expect the same behavior for expired pools

**Comment by zaibon** [comment]
@LeeSmet you thought on this one ?

I guess today the logic is, as soon as the pool expire, all the attached workloads are deleted. But it sounds that there are cases where you could run out of one specific resource, let's say CU, and thus you could still have enough SU to maintain volumes and other resource that only consume SU.

So I would say the proper logic should be, once a pool reach a point where one of the resource is exhausted, then only the workloads consuming this resource should be cancelled and not all of the attached workloads.

**Comment by LeeSmet** [comment]
Indeed we currently remove all workloads in the pool. 

> So I would say the proper logic should be, once a pool reach a point where one of the resource is exhausted, then only the workloads consuming this resource should be cancelled and not all of the attached workloads.

Yeah, I think I mentioned this somewhere as well in the past (not sure where), and it is possible.

However, I would like to point out that there is no "free workload". The only reason that networks and gateways are currently free is because Network Units are not implemented yet (whatever happened to those anyway?). As a result, we simply don't measure their usage currently, and thus you don't pay for them, which gives the impression that the workload is free. But it is not, or rather, it should not be. This means, all in all, that once this (NU) is implemented, behavior for expired pools _will_ be the same as behavior for empty pools: you won't be able to deploy anything on them.

So ultimately, yes, we should implement selective removal of workloads if not all resources in the pool are expired. But, it should also be known that "free workloads" is just a temporary state which is the unfortunate result of not having network units yet, and any code which relies on these primitives actually being free _will_ break in the future

**Comment by zaibon** [comment]
yep I already mentioned that these "free" workloads should not be something to build on top cause all code relying on this behavior will automatically break they day NU are introduced.

But the general idea to only delete workloads that actually out of resource is good.  I'll rename this issue.

**Comment by zaibon** [comment]
Fix is live on devnet
