### ISSUE TITLE
Add concept of network units (NU)

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/tfexplorer#180]
Currently we have compute units (CU) and storage units (SU). It is clear however that we also need network units. The lack of these leads to certain primitives currently being free to use, while they obviously should not. Another side effect, as a result of #178, is that these primitives will now essentially live forever, unless manually decomissioned

**Comment by zaibon** [comment]
The network unit concept was briefly discussed a while back. The idea is to be able to track how much network traffic is consumed by a user/workload. The definition of a NU was 1GiB of traffic. 
This definition is very vague a requires to be extended. Some open questions:
- What is the definition of traffic ? 
- is it all inbound and outbound traffic. 
- Is it traffic between nodes ? 
- is it traffic to public internet ? 
- What about the gateway ?
- What happens when you run out of NU ?

Once we have answered these questions, Then we can start thinking about implementation and how to track the consumption.

**Comment by xmonader** [comment]
@m-motawea please follow up here so we have an overview on what's needed to change in our side
