### ISSUE TITLE
The explorer provides data that allows workload redeployment without extra authorization.

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/tfexplorer#192]
When creating a new deployment, the request contains the info of the workload along with its signature. The explorer provides all of this data with the signature. This way anyone can replicate the request and deploy this workload again.

**Comment by muhamadazmy** [comment]
May be signature should be hidden forever from the API. only accepted on reservation creation.

**Comment by zaibon** [comment]
yeah I have the same thought. These signature needs to be part of the requests sent to the explorer, but there is no point storing them.

**Comment by muhamadazmy** [comment]
I think this is one of the issues that will naturally get solved after moving to a real blockchain. but for now we can work around the problem (i think) as follows:
- User creates a reservation object the same we do right now. (Only the immutable part is included in the signature) 
- Then on creating the request the user also need to provide a valid httpsig request.
- The httpsig request identity must match the reservation identity.

This way if a user trying to recreate an exact copy of the same reservation, the explorer will still reject the request because the user will fail to provide a proof he owns the sk associated with that user identity.

**Comment by LeeSmet** [comment]
That does sound like a good solution, provided the httpsig covers a field like timestamp (which I think it does?) and it is enforced that this is not outdated.

Alternatively, we could introduce a `nonce` field with some random bytes, include this in the signature, and enforce uniqueness of this field for every new workload. Since the nonce is shown in the explorer when doing a lookup, this is more explicit than the httpsig which is probably only validated when the request comes in and then discarded (though that is not a problem I think)

Imo both should be fine, the httpsig could be a bit nicer since it does not clutter the workload definition any more than necessary.

**Comment by muhamadazmy** [comment]
if we use the nonce we then will need to index plus the overhead of the look up on each new create operation. So I (IMHO) prefer the httpsig solution
