### ISSUE TITLE
PublicIP:Add new reservation type public-ip 

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tfexplorer#210]
The new type asks for a public ip that forwards the traffic to a private IP on the user overlay network

input
```yaml
  destination: <private-ip>
```
output:
```yaml
  public: <public-ip>
```

Part Of: https://github.com/threefoldtech/home/issues/925

**Comment by LeeSmet** [comment]
Perhaps we should have the pub IP as an input as well rather than an output. That way there does not need to be any logic on the explorer except for a simple check to see if the IP is still free. Similar to how the networkresource also requires the user to set the wg listen port. If a duplicate is used, there is an error (though listen port is not checked in the explorer afaik, which we will need to do for the IP)
