### ISSUE TITLE
PublicIP: extend farm data with available public pools

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tfexplorer#211]
## The farm object need to be extended to:
- Add list of `ip range`
- An  `ip range` can be defined as
  - A full subdomain
  - List of pubic IPs 
  - Single IP
- Each pool also has a list of reserved IPs which is defined as a map to reservation ID that holds ownership of this IP.
> Is it better to query this information by aggregating all the reserved IPs from the database ? This is a heavy task to do to validate the free IPs each time.

## API Endpoints
A farmer can manage his pools as follows
- Base URL `/api/v1/farms/<farmid>`
- `POST <base-url>/ranges` add a new range
- `GET <base-url>/ranges` (not needed since this is part of the farm object after all)
- `DEL <base-url>/ranges/<id>` (validate that are no ip used from that range)

Part Of: https://github.com/threefoldtech/home/issues/925

**Comment by LeeSmet** [comment]
> An ip range can be defined as
>
>  -  A full subdomain
>  -  List of pubic IPs
>  -  Single IP

I think as far as the explorer goes, we should just care about a list of public IP's in the data model and the api endpoints. This keeps operation simple. Client side tools can easily expand a subnet to a list op IP's (in case anyone ever adds a giant subnet). And a single IP is just a list of IP's with 1 element.

That way the data model can just be something extremely simple like:

```javascript
[
  {
    "addr": "xxx.xxx.xxx.xxx",
    "used": false
  },
  {
    ...
  }
]
```

**Comment by DylanVerstraete** [comment]
Can't we just use farm-update endpoint for all this since we just wanna keep a list of IP's on a farmer object?

**Comment by LeeSmet** [comment]
You could I guess, but keep in mind that for deletion of IP's you must first validate that they are not currently in use. So every update will need to first check that the field of IP addrs is the same as it used to be, and if not, check that any removed ip is not used. Also, since the GET will return if an ip is used or not, the POST will also include this property, meaning you need to check that existing IP values are not flipped, and new IP's are in `used == false` state. Or you can make the POST take a list of IP's and modify this to the object on the backend, but that means that a client will need to reduce the object to a list of IP's under the hood as well

**Comment by muhamadazmy** [comment]
@LeeSmet I don't get what you suggest ? When I say the farmer needs to have a list of iprange defined, it can be a subnet or a subnet of single IP
```
10.200.1.0/24
10.200.1.5/32
```
then we get the 'used' ips part
which is just a list of all ips used from that farmer ?

So clients can expand the ranges, and find the free spots
