### ISSUE TITLE
harden the sshkey input

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#218]
Because of different line endings reservations might end up with some errors like https://explorer.testnet.grid.tf/api/v1/reservations/workloads/509001
```
message: "failed to install k3s: could not run vm: 2020-11-23T09:37:47.223845717 [509001-1:ERROR:src/firecracker/src/main.rs:268] Configuration for VMM from one single json failed: BootSource(InvalidKernelCommandLine("Command line string contains non-printable ASCII character")) : failed to spawn vm machine process '509001-1'",
epoch: 1606124271,
node_id: "CLfM5SEqquRGzoaM8xxh2hxJqzd2h8SRgMfHzd9jyACS"
},
```
- should skip empty entries
- should trim line endings \r, \r\n, \n correctly 

- PR fix in sdk https://github.com/threefoldtech/js-sdk/pull/1718

**Comment by muhamadazmy** [comment]
We can't change user intput in the explorer otherwise the signature won't match anymore. hence the fixing of the input should only be done in the client side. and if the node fails to process the user input, it fails.

In other words, we can't do such clean up in the explorer side. I can see this has been fixed already in the sdk, so I will close this issue
