### ISSUE TITLE
better API to verify pools extensions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#265]
Right now we do the payment and check against an update of the available cus/sus. The problem is if you have active workloads consuming the pool, extending pools with small values and detecting that would be very tricky (not noticeable). IMO, the easiest would be `last_extended_at` field in the pool information to reflect the extension

**Comment by LeeSmet** [comment]
I personally don't like this construction. While it works on low access pools, that is pools which are only topped up every so often, it is perfectly possible to run 2 top ups at the same time. In which case you'll still miss one of them.

Given that the whole payment thing is asynchronous by design, I think some kind of poll system on the capacity reservation itself would be better. I.e, we should add an endpoint where a given capacity reservation ID can be queried, which then returns the raw reservation (or only part of it, should some things need some stripping to avoid leaking data). That way, API's built on top of the payment system can verify that a payment has been processed successfully with an exponential timeout, or after a user presses a button to claim he paid (for example)

**Comment by muhamadazmy** [comment]
I added a new endpoint `https://explorer.testnet.grid.tf/api/v1#/pools/getpaymentinfo` to be able to fetch the payment information from explorer perspective.

The flag, paid, canceled, and cause can be used to track the state of the payment. If canceled (and refunded) the cause should hold the reason for the cancellation.
