### ISSUE TITLE
dedicated nodes: nodes that get reservation only from a single user id

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tfexplorer#292]
The idea is that a dedicated node is that a node can have a flag set with a certain user id. Once this flag is set, the explorer will only accept workloads to that node from only this user.

API for the farmer to update the node `dedicated`  flag of a node.

**Comment by xmonader** [comment]
I think maybe we need a way to handle the following 
- creating pool containing a dedicated node should expand to the full resources of that node
- prevent the creation of any other pools contains a dedicated node 

I'm sure this is going to be tricky, because when also on the sdk side we create a pool we make sure to include all of the nodes of the farm, probably we will have to filter out the nodes flagged as dedicated by default.

**Comment by weynandkuijpers** [comment]
@xmonader your understanding is 100% correct. :-)

**Comment by xmonader** [comment]
If the feature going to be limited to the VDC usage only, I think it won't be the easiest for us.

As far as I understand from the PR it's a user id that is tied to the node, and in the VDC system (we don't own the reservations, we create an identity for the user to own that VDC workload, and life cycle) our relation as a VDC to these reservations are as "sponsoring" only, so yes, the explorer should be able to know if the request is coming from someone "sponsored" by the VDC or not, but also this needs to be done in the provisioning phase of the VDC, if you try to extend it later "on a different farm " It won't work as the VDC won't be able to sign/sponsor these reservations as they run on a remote machine.

I guess maybe if we keep the user out of the equation, would be helpful in 2.6/2.7 and in 3.0 as well

**Comment by LeeSmet** [comment]
Full on "reserving" a node for any user based on that user sending a reservation, which then forces him to pay for the full node and allowing him to deploy actual workloads for free is something which will require a major rework in the way the payment flow and pool system work. Considering that the explorer will be removed in 3.0, I don't think its a particularly good idea to implement the full feature at the moment. Especially given that there is a straightforward way to do this once 3.0 is live with the farmer bot.

So after reading through this and a quick call with @xmonader ,  and considering that currently the main usecase seems to be dedicated nodes specifically for kubernetes vm's, I propose the following:

We add a special `size` in the kubernetes vm which essentially means  "however much resources the node has left". Since the node trusts the explorer to do signature validation, we can inject the remaining free resources into the reservation after the explorer validates the signatures. The explorer knows this, as it knows both the total resources on a node and the amount of used resources. This also allows us to still have a static calculation of the used resources used.

**Comment by weynandkuijpers** [comment]
@LeeSmet IS there a new issue / story in which your suggestions is taken forward?  If so - can you record the link / issues number here?

**Comment by LeeSmet** [comment]
> @LeeSmet IS there a new issue / story in which your suggestions is taken forward? If so - can you record the link / issues number here?

There is not. If everyone agrees that this is a good way forward, the issue can ofcourse be created

**Comment by muhamadazmy** [comment]
We added support for a new special size for k8s (-1) 
the `-1` size will do the following:
- the explorer will look up the node and calculate the available capacity
- the explorer will modify the reservation by adding the maximum CPU and MEM available on the node, and 50G of ssd storage
- the reservation is sent to the node.
- this mechanism will allow to create a k8s nodes that "eats up" all available resources (CPU/MEM) on the node.

> Note: the node can still accept ZDB reservations from other users. But since there is no cpu and memory left, it will reject reservations for vms and containers.

**Comment by muhamadazmy** [comment]
Just some notes on why it's implemented this way:
- Implement a fully dedicated node (a single user can only use the node) requires a lot of changes to how the billing system works on the explorer, the changes will need a lot of time and effort that is rather be directed to version 3.0 since the explorer itself will be obsolete anyway
- The k8s special size (-1) is some middle solution where node resources is assigned to a single k8s vm.
- The reason the disk size is set to 50G is because the explorer does not know about single disks information on the node, only total capacity. So for example, if a node reports capacity of 500G the explorer does not know if it's 1x500G disk or 10x50G disks. Hence we used an avg size of 50G hence the explorer can do proper prices calculations for the used capacity
- Another solution is to may be ask the node to try allocate a full disk or max size available of certain disk type. While this can be done on VM size, the explorer will not know how much was allocated and then billing information will still be wrong.
- The fully dedicated node (only a single entity can deploy) can be very easily and cleanly implemented in tfgrid 3.0
