### ISSUE TITLE
network monitoring / billing

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#302]
After discussion with @despiegk, we can't go live without mechanisms/ pricing for network and bandwidth control / absue protection. elevating https://github.com/threefoldtech/zos/discussions/1229 this discussion

- farmer should be able to set NU price (that's different everywhere)
- should be able to monitor traffic usage
- should be able to limit bandwidth 
...

TODO...

Links:
https://github.com/threefoldtech/zos/discussions/1229

**Comment by muhamadazmy** [comment]
This is ver complex to implement for 2.X because of how billing is done. The pools are pre-paid so user actually pays for capacity before he actually deploy anything. While this is okay for workloads like containers, volumes, vms, etc.. before we can know exactly how much they consume (in terms of CPU/MEMORY) over a certain amount of time. we can then tell when the pool will get depleted. 
Unlike network witch can't be foreseen. Also the network workload is very special since it is:
- Can span multiple pools
- Can span multiple farms 
- And of course spans multiple nodes

So what can be done:
- Node can (to be added code) calculate a network consumption (per network)
- Node then can report the usage to the explorer 
- Explorer can then return 1 of 2 responses:
  - Green light (network may still serve traffic to this user network -namespace-)
  - Red light (network is paused -we pull the right wires to disable it-)
- The explorer when usage is reported can deduct this value from the pool
- If the remaining capacity is less than or equal zero the red light response is returned
- If the remaining capacity is still greater than zero the green light response is returned
- The pool NU should allow values less than 0, so duo to the discrete nature of reporting a node can allow traffic while the pool is empty this way the user will have to pay what he consumed if he wants to charge the pool 

To consider:
- the network can span multiple farms. (and i think multiple pools) so it might be NOT possible to use the current capacity pool, and instead we will have to create a NetworkPool per network.

TODO.. specs

**Comment by LeeSmet** [comment]
In the interest of keeping this compact and understandable, I will start with only the zos workloads (no gateways, though the concept should be fairly extendable to those). If we look at the current workloads, we see that there are only 2 network workloads: `network` and `public ip`. While most other workloads have networking, they do that by leveraging one of the 2 previously mentioned "building blocks". As such, we can restrict the workloads which will consume `network units` (`NU`'s) to these 2.

While fitting the concept of NU's in the current pools is not ideal, I think it is viable, as long as we accept that it is an imperfect solution. Essentially we can perform the same "tricks" as with the SU and CU in the capacity pools. This makes sure that the flow for NU is the same as the flow for all other units in the pool, and doesn't involve developing a whole new flow for a soon to be deprecated system (i.e. consumption being reported from the node to the explorer).

## First things first:

>Unlike network witch can't be foreseen. Also the network workload is very special since it is:
>
>  -  Can span multiple pools
>  -  Can span multiple farms
>  -  And of course spans multiple nodes

> the network can span multiple farms. (and i think multiple pools) so it might be NOT possible to use the current capacity pool, and instead we will have to create a NetworkPool per network.

This is not a problem imo. Recall that the concept of the `network` only exists on the higher level. On the low lever (what zos and the explorer care about), we introduced the concept of the `network resource` with the introduction of the capacity pools. This solves the above issues. Every network resource is deployed on 1 node, meaning it does not span multiple farms, and is tied to a single pool. This means we bill every network resource, and thus every node, separately. In practice, this will mean that some network resources might suddenly disappear, causing the workloads on top to become unreachable, which is fine (there are some caveats, see below).

## Implementation

### Workload changes

In order to support this feature, both `network resource` and `public IP` will need to have a new field, which is a measurement of the network throughput they support. 

### Explorer pools

In the original capacity pool spec, it was said that both SU and CU, although single units, represent 2 units: an `allocation of resources` over some `time`. It is up to the actual workload to see how these units are used. A short lived workload which allocates and uses a lot of resources, or a longer lived workload, using less resources. If we look at the workloads, we can see that we actually pay for the maximum usage the entire time. For instance, a VM with 4 cores and 8GB of memory is billed for the entire duration as 4 cores and 8GB of memory, even if it only ever uses 2 cores and 4 GB of memory. In other words, the workloads bill the `reserved capacity`, not the `actually used capacity`. If we map this concept back to the capacity pool, we see that the pool units can be considered an `allocation over time`. As an example, if we have a workload using 4 CU, and it lives for 100 seconds, we use 400 CUs, i.e. the pool uses 400 CU seconds.

The network is actually the same. If we consider the bandwidth limit (say 10 Mib per second) to be the reservation, we can use that over some amount of time. Rather than landing at a `NUs` unit however, we land at simple `NU`, where an NU will be a byte (or similar). As such, a capacity pool (for networking) is filled with simple `bytes` or `bits`. This can be seen by taking the unit of the bandwidth, either `bytes per second` or `bits per second`, and the second unit, time, as `seconds`. Multiplication leaves us with `bytes` or `bits` respectively. It should be noted that this will grossly overcharge users, even more so than the other workloads. But that feels like an acceptable tradeoff at this point, and can be mitigated by setting lower prices for NU's (for now).

### Zos

In general, we should use something like `tc` to limit the bandwidth of the right interfaces, according to the workload definition. This is something `networkd` should easily be able to support.

#### Network resource

There are 3 cases for a network resource: 

- traffic coming from a workload in the network resource, going to another workload in the same network resource.
- traffic coming from a workload in the network resource, going out to the public internet.
- traffic going from the network resource to another network resource. Since we can't know if this different network resource is on the same node or the same farm (and since farms don't need to be in the same location and therefore the same LAN), we will consider this traffic to be external. 

For the first case: internal traffic should not be billed, and can thus be ignored. This means that there is some advantage to workload locality. Multiple workloads in the same network resource will not consume any NU's when communicating with one another. Furthermore, there is no bandwidth limit, as in the end, the network is not used for this.

For the second, and by extension third case: we limit the bandwidth of the interfaces going out in accordance to what is specified. The annoying part is that we have a discrete interface for inter-network-resource, and outgoing traffic, which might be tricky to get a proper limit in place.

#### Public IP

The public IP is essentially represented by an interface (and some firewall rules). Whenever this interface is created, we can set the correct bandwidth limits.

## Open questions, potential issues and caveats

- Network resources will now be able to die because they consume some resource, which gets emptied. Currently workloads don't deal well with this. To solve this, I think it would be best to introduce a new `paused` or similar state, which is what a network resource goes into if the associated pool runs out of NU. In this mode, zos can restrict all bandwidth limited interfaces to not allow any traffic (so workloads on the same network resource could still communicate). The explorer can run a periodic routine which only marks network resources as to delete if no other workload is using them anymore. Of course the user can still manually delete.
- It should be possible to specify 0 bandwidth for a network resource. It won't be billed, but only allow workloads on the same node to communicate.
- The above assumes `bandwidth` goes both ways. So 10 Mibs would give you both 10 Mibs up and down, ultimately leading to 20 Mibs total (so u could technically use double the capacity of your NU's). We could also assume this is the grand total, meaning you only get half, i.e. 5 Mibs up and 5 Mibs down. In an ideal world, we could set a limit of `up` and `down` aggregated (so it handles that dynamically, i.e. you have 10 Mibs up + down at any instance, but depending on the actual load your up and down might fluctuate to compensate for one another). If this is not possible, we could split the `bandwidth` parameter in the network resource and public ip workload into 2 halves. One for up and one for down. This is more flexible, but also ever so slightly more cumbersome, and will have people potentially put in dumb values.
- As mentioned we grossly overcharge in this scheme. I don't think that is an issue, we already overcharge for other workloads in theory. But to compensate, we might need to drop prices so low that it doesn't _really_ protect from abuse that much.
- Should there be a max up and down? and if so, should the farmer be able to configure this? I feel yes, with some sane defaults, so regular farmers don't have to care, and big farmers can tune for their setup.
- ...

**Comment by muhamadazmy** [comment]
@despiegk can we get an approval on the proposed solution for this issue?

**Comment by xmonader** [comment]
Double checked with Kristof, It won't be done for 2.X let's address that in 3.X

**Comment by despiegk** [comment]
we took other approach for 2.9
