### ISSUE TITLE
Change FreeTFT definition

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/tfexplorer#50]
We had some feedback that the current definition of FreeTFT creates a quite big split in grid usability.

At the moment a node marked as free to use can only be paid with FreeTFT. Which means you ca basically have 2 separate grid. Once you can use with FreeTFT and one you can use with TFT.

An idea to avoid this is to change the definition of "free to use" for a node. Instead of only being able to pay using FreeTFT, it would instead mean you can pay with TFT or FreeTFT.
The reservation object already accept a list of currency the user is able to pay with. So based on the node free to use status. The escrow could decide what currency to use.

@grimpy @LeeSmet @andhartl

**Comment by LeeSmet** [comment]
While this idea does make a lot of sense, it also creates another issue. Right now we can get away with a small amount of free to use nodes, because the amount of FreeTFT is limited per user, so the usage of free nodes is also limited as well. If these nodes can be used for regular reservations, the amount of workloads on them will probably be larger. And not everyone will want to make their nodes free to use. So the amount of space for actual free trial workloads might become smaller I think

**Comment by zaibon** [comment]
> the amount of space for actual free trial workloads might become smaller I think

Reason being that the capacity of a node is finite and it will maybe used more thus leaving less space for free capacity ?

**Comment by LeeSmet** [comment]
exactly

**Comment by gmachtel** [comment]
> exactly

When you allow the farmer to accept both TFT and FreeTFT, he will very likely be positive about accepting FreeTFT as well. So yes, you’re not sure that there will be enough capacity for FreeTFT but on the other hand there will be more nodes available too. And moreover, it won’t split the grid in two pieces anymore, the major drawback of the current definition. 
I’d even reverse also the default value for farmers to ‘accept both TFT and FreeTFT’. This way, the ‘burden’ of people exploring freely the grid is spread over equally among all farmers.

**Comment by LeeSmet** [comment]
> When you allow the farmer to accept both TFT and FreeTFT, he will very likely be positive about accepting FreeTFT as well.

I don't see a reason why that would be the case. The other way around, sure. But why would a farmer be happy that people can use his capacity for free if they can also be paid for it?

**Comment by gmachtel** [comment]
> > When you allow the farmer to accept both TFT and FreeTFT, he will very likely be positive about accepting FreeTFT as well.
> 
> I don't see a reason why that would be the case. The other way around, sure. But why would a farmer be happy that people can use his capacity for free if they can also be paid for it?

That's how publicity works. A coupon such as FreeTFT is like a coupon in a shop. Shops accept to distribute free samples because this way, people get a taste of what the product is about, of course under the condition that distribution of these samples (FreeTFT) is not exaggerated. But that is not the case: distribution of FreeTFT is hidden behind an application form, so we have full control over how many FreeTFTs are circulating.

**Comment by LeeSmet** [comment]
Yes publicity is one thing, but making this opt out feels like way want to force the farmer to make publicity on behalf of the foundation, which is still the party that made the grid. Unlike real life, the farmers here are also trying to sell the same product, so the real life free sample, which also serves to compare the product with the competition, does not apply here.

And most importantly, having people deploy free stuff actually costs money for the farmer. Which for me is reason enough to always keep this opt in.

**Comment by gmachtel** [comment]
OK, just afraid then that the added value of FreeTFT will remain limited, and that will then give a bad impression to the user. So publicity is not only benefiting the foundation but also for the farmer. 
And opt-in or opt-out, turn the switch is really simple.
